<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Balance.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Balance extends ZilliqaDataType {

	/**
	 * @var ZilliqaQuantity
	 */
	public $balance;

	/**
	 * @var ZilliqaQuantity
	 */
	public $nonce;

	/**
	 * @param ZilliqaQuantity $balance
	 * @param ZilliqaQuantity $nonce
	 */
	public function __construct(ZilliqaQuantity $balance, ZilliqaQuantity $nonce) {
		$this->balance = $balance;
		$this->nonce = $nonce;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'balance' => 'ZilliqaQuantity',
			'nonce' => 'ZilliqaQuantity',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'balance' => !is_null($this->balance) ? $this->balance->val() : null,
			'nonce' => !is_null($this->nonce) ? $this->nonce->val() : null,
		];
	}
}