<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type BlockchainInfo.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class BlockchainInfo extends ZilliqaDataType {

	/**
	 * @var ZilliqaQuantity
	 */
	public $CurrentDSEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $CurrentMiniEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $DSBlockRate;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumDSBlocks;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumPeers;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTransactions;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxBlocks;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxnsDSEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxnsTxEpoch;

	/**
	 * @var ShardingStructure[]
	 */
	public $ShardingStructure;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TransactionRate;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TxBlockRate;

	/**
	 * @param ZilliqaQuantity $CurrentDSEpoch
	 * @param ZilliqaQuantity $CurrentMiniEpoch
	 * @param ZilliqaQuantity $DSBlockRate
	 * @param ZilliqaQuantity $NumDSBlocks
	 * @param ZilliqaQuantity $NumPeers
	 * @param ZilliqaQuantity $NumTransactions
	 * @param ZilliqaQuantity $NumTxBlocks
	 * @param ZilliqaQuantity $NumTxnsDSEpoch
	 * @param ZilliqaQuantity $NumTxnsTxEpoch
	 * @param array $ShardingStructure Array of ShardingStructure
	 * @param ZilliqaQuantity $TransactionRate
	 * @param ZilliqaQuantity $TxBlockRate
	 */
	public function __construct(ZilliqaQuantity $CurrentDSEpoch, ZilliqaQuantity $CurrentMiniEpoch, ZilliqaQuantity $DSBlockRate, ZilliqaQuantity $NumDSBlocks, ZilliqaQuantity $NumPeers, ZilliqaQuantity $NumTransactions, ZilliqaQuantity $NumTxBlocks, ZilliqaQuantity $NumTxnsDSEpoch, ZilliqaQuantity $NumTxnsTxEpoch, array $ShardingStructure, ZilliqaQuantity $TransactionRate, ZilliqaQuantity $TxBlockRate) {
		$this->CurrentDSEpoch = $CurrentDSEpoch;
		$this->CurrentMiniEpoch = $CurrentMiniEpoch;
		$this->DSBlockRate = $DSBlockRate;
		$this->NumDSBlocks = $NumDSBlocks;
		$this->NumPeers = $NumPeers;
		$this->NumTransactions = $NumTransactions;
		$this->NumTxBlocks = $NumTxBlocks;
		$this->NumTxnsDSEpoch = $NumTxnsDSEpoch;
		$this->NumTxnsTxEpoch = $NumTxnsTxEpoch;
		$this->ShardingStructure = $ShardingStructure;
		$this->TransactionRate = $TransactionRate;
		$this->TxBlockRate = $TxBlockRate;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'CurrentDSEpoch' => 'ZilliqaQuantity',
			'CurrentMiniEpoch' => 'ZilliqaQuantity',
			'DSBlockRate' => 'ZilliqaQuantity',
			'NumDSBlocks' => 'ZilliqaQuantity',
			'NumPeers' => 'ZilliqaQuantity',
			'NumTransactions' => 'ZilliqaQuantity',
			'NumTxBlocks' => 'ZilliqaQuantity',
			'NumTxnsDSEpoch' => 'ZilliqaQuantity',
			'NumTxnsTxEpoch' => 'ZilliqaQuantity',
			'ShardingStructure' => '[ShardingStructure]',
			'TransactionRate' => 'ZilliqaQuantity',
			'TxBlockRate' => 'ZilliqaQuantity',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'CurrentDSEpoch' => !is_null($this->CurrentDSEpoch) ?? $this->CurrentDSEpoch->val(),
			'CurrentMiniEpoch' => !is_null($this->CurrentMiniEpoch) ?? $this->CurrentMiniEpoch->val(),
			'DSBlockRate' => !is_null($this->DSBlockRate) ?? $this->DSBlockRate->val(),
			'NumDSBlocks' => !is_null($this->NumDSBlocks) ?? $this->NumDSBlocks->val(),
			'NumPeers' => !is_null($this->NumPeers) ?? $this->NumPeers->val(),
			'NumTransactions' => !is_null($this->NumTransactions) ?? $this->NumTransactions->val(),
			'NumTxBlocks' => !is_null($this->NumTxBlocks) ?? $this->NumTxBlocks->val(),
			'NumTxnsDSEpoch' => !is_null($this->NumTxnsDSEpoch) ?? $this->NumTxnsDSEpoch->val(),
			'NumTxnsTxEpoch' => !is_null($this->NumTxnsTxEpoch) ?? $this->NumTxnsTxEpoch->val(),
			'ShardingStructure' => !is_null($this->ShardingStructure) ?? \Zilliqa\Zilliqa::valueArray($this->ShardingStructure, 'ShardingStructure'),
			'TransactionRate' => !is_null($this->TransactionRate) ?? $this->TransactionRate->val(),
			'TxBlockRate' => !is_null($this->TxBlockRate) ?? $this->TxBlockRate->val(),
		];
	}
}