<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Exception.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Exception extends ZilliqaDataType {

	/**
	 * @var ZilliqaNumber
	 */
	public $line;

	/**
	 * @var ZilliqaString
	 */
	public $message;

	/**
	 * @param ZilliqaNumber $line
	 * @param ZilliqaString $message
	 */
	public function __construct(ZilliqaNumber $line, ZilliqaString $message) {
		$this->line = $line;
		$this->message = $message;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'line' => 'ZilliqaNumber',
			'message' => 'ZilliqaString',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'line' => !is_null($this->line) ?? $this->line->val(),
			'message' => !is_null($this->message) ?? $this->message->val(),
		];
	}
}