<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Message.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Message extends ZilliqaDataType {

	/**
	 * @var ZilliqaQuantity
	 */
	public $_amount;

	/**
	 * @var ZilliqaHash
	 */
	public $_recipient;

	/**
	 * @var ZilliqaString
	 */
	public $_tag;

	/**
	 * @var ZilliqaString[]
	 */
	public $params;

	/**
	 * @param ZilliqaQuantity $_amount
	 * @param ZilliqaHash $_recipient
	 * @param ZilliqaString $_tag
	 * @param array $params Array of ZilliqaString
	 */
	public function __construct(ZilliqaQuantity $_amount, ZilliqaHash $_recipient, ZilliqaString $_tag, array $params) {
		$this->_amount = $_amount;
		$this->_recipient = $_recipient;
		$this->_tag = $_tag;
		$this->params = $params;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'_amount' => 'ZilliqaQuantity',
			'_recipient' => 'ZilliqaHash',
			'_tag' => 'ZilliqaString',
			'params' => '[ZilliqaString]',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'_amount' => !is_null($this->_amount) ? $this->_amount->val() : null,
			'_recipient' => !is_null($this->_recipient) ? $this->_recipient->val() : null,
			'_tag' => !is_null($this->_tag) ? $this->_tag->val() : null,
			'params' => !is_null($this->params) ? \Zilliqa\Zilliqa::valueArray($this->params, 'ZilliqaString') : null,
		];
	}
}