<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Message.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Message extends ZilliqaDataType {

	/**
	 * @var ZilliqaQuantity
	 */
	public $_amount;

	/**
	 * @var ZilliqaBech32
	 */
	public $_recipient;

	/**
	 * @var ZilliqaString
	 */
	public $_tag;

	/**
	 * @var ZilliqaString[]
	 */
	public $params;

	/**
	 * @param ZilliqaQuantity $_amount
	 * @param ZilliqaBech32 $_recipient
	 * @param ZilliqaString $_tag
	 * @param array $params Array of ZilliqaString
	 */
	public function __construct(ZilliqaQuantity $_amount, ZilliqaBech32 $_recipient, ZilliqaString $_tag, array $params) {
		$this->_amount = $_amount;  
		$this->_recipient = $_recipient;  
		$this->_tag = $_tag;  
		$this->params = $params;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'_amount' => 'ZilliqaQuantity',
			'_recipient' => 'ZilliqaBech32',
			'_tag' => 'ZilliqaString',
			'params' => '[ZilliqaString]',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'_amount' => $this->_amount->val(),
			'_recipient' => $this->_recipient->val(),
			'_tag' => $this->_tag->val(),
			'params' => \Zilliqa\Zilliqa::valueArray($this->params, 'ZilliqaString'),
		];
	}
}