<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type MicroBlockInfo.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class MicroBlockInfo extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash
	 */
	public $MicroBlockHash;

	/**
	 * @var ZilliqaNumber
	 */
	public $MicroBlockShardId;

	/**
	 * @var ZilliqaHash
	 */
	public $MicroBlockTxnRootHash;

	/**
	 * @param ZilliqaHash $MicroBlockHash
	 * @param ZilliqaNumber $MicroBlockShardId
	 * @param ZilliqaHash $MicroBlockTxnRootHash
	 */
	public function __construct(ZilliqaHash $MicroBlockHash, ZilliqaNumber $MicroBlockShardId, ZilliqaHash $MicroBlockTxnRootHash) {
		$this->MicroBlockHash = $MicroBlockHash;
		$this->MicroBlockShardId = $MicroBlockShardId;
		$this->MicroBlockTxnRootHash = $MicroBlockTxnRootHash;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'MicroBlockHash' => 'ZilliqaHash',
			'MicroBlockShardId' => 'ZilliqaNumber',
			'MicroBlockTxnRootHash' => 'ZilliqaHash',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'MicroBlockHash' => !is_null($this->MicroBlockHash) ? $this->MicroBlockHash->val() : null,
			'MicroBlockShardId' => !is_null($this->MicroBlockShardId) ? $this->MicroBlockShardId->val() : null,
			'MicroBlockTxnRootHash' => !is_null($this->MicroBlockTxnRootHash) ? $this->MicroBlockTxnRootHash->val() : null,
		];
	}
}