<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type MinerInfo.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class MinerInfo extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash[]
	 */
	public $dscommittee;

	/**
	 * @var Shard
	 */
	public $shards;

	/**
	 * @param array $dscommittee Array of ZilliqaHash
	 * @param $shards
	 */
	public function __construct(array $dscommittee, $shards) {
		$this->dscommittee = $dscommittee;  
		$this->shards = $shards;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'dscommittee' => '[ZilliqaHash]',
			'shards' => 'Shard',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'dscommittee' => \Zilliqa\Zilliqa::valueArray($this->dscommittee, 'ZilliqaHash'),
			'shards' => $this->shards->toArray(),
		];
	}
}