<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type TransactionCreated.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class TransactionCreated extends ZilliqaDataType {

	/**
	 * @var ZilliqaString
	 */
	public $Info;

	/**
	 * @var ZilliqaHash
	 */
	public $TranID;

	/**
	 * @param ZilliqaString $Info
	 * @param ZilliqaHash $TranID
	 */
	public function __construct(ZilliqaString $Info, ZilliqaHash $TranID) {
		$this->Info = $Info;
		$this->TranID = $TranID;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'Info' => 'ZilliqaString',
			'TranID' => 'ZilliqaHash',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'Info' => !is_null($this->Info) ? $this->Info->val() : null,
			'TranID' => !is_null($this->TranID) ? $this->TranID->val() : null,
		];
	}
}