<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Transaction.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Transaction extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash
	 */
	public $ID;

	/**
	 * @var ZilliqaQuantity
	 */
	public $amount;

	/**
	 * @var ZilliqaQuantity
	 */
	public $gasLimit;

	/**
	 * @var ZilliqaQuantity
	 */
	public $gasPrice;

	/**
	 * @var ZilliqaNumber
	 */
	public $nonce;

	/**
	 * @var Receipt
	 */
	public $receipt;

	/**
	 * @var ZilliqaHash
	 */
	public $senderPubKey;

	/**
	 * @var ZilliqaSignature
	 */
	public $signature;

	/**
	 * @var ZilliqaHash
	 */
	public $toAddr;

	/**
	 * @var ZilliqaNumber
	 */
	public $version;

	/**
	 * @var ?ZilliqaString
	 */
	public $code;

	/**
	 * @var ?ZilliqaString
	 */
	public $data;

	/**
	 * @param ZilliqaHash $ID
	 * @param ZilliqaQuantity $amount
	 * @param ZilliqaQuantity $gasLimit
	 * @param ZilliqaQuantity $gasPrice
	 * @param ZilliqaNumber $nonce
	 * @param $receipt
	 * @param ZilliqaHash $senderPubKey
	 * @param ZilliqaSignature $signature
	 * @param ZilliqaHash $toAddr
	 * @param ZilliqaNumber $version
	 * @param ?ZilliqaString $code
	 * @param ?ZilliqaString $data
	 */
	public function __construct(ZilliqaHash $ID, ZilliqaQuantity $amount, ZilliqaQuantity $gasLimit, ZilliqaQuantity $gasPrice, ZilliqaNumber $nonce, $receipt, ZilliqaHash $senderPubKey, ZilliqaSignature $signature, ZilliqaHash $toAddr, ZilliqaNumber $version, ?ZilliqaString $code = null, ?ZilliqaString $data = null) {
		$this->ID = $ID;
		$this->amount = $amount;
		$this->gasLimit = $gasLimit;
		$this->gasPrice = $gasPrice;
		$this->nonce = $nonce;
		$this->receipt = $receipt;
		$this->senderPubKey = $senderPubKey;
		$this->signature = $signature;
		$this->toAddr = $toAddr;
		$this->version = $version;
		$this->code = $code;
		$this->data = $data;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'ID' => 'ZilliqaHash',
			'amount' => 'ZilliqaQuantity',
			'gasLimit' => 'ZilliqaQuantity',
			'gasPrice' => 'ZilliqaQuantity',
			'nonce' => 'ZilliqaNumber',
			'receipt' => 'Receipt',
			'senderPubKey' => 'ZilliqaHash',
			'signature' => 'ZilliqaSignature',
			'toAddr' => 'ZilliqaHash',
			'version' => 'ZilliqaNumber',
			'code' => 'ZilliqaString',
			'data' => 'ZilliqaString',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'ID' => !is_null($this->ID) ? $this->ID->val() : null,
			'amount' => !is_null($this->amount) ? $this->amount->val() : null,
			'gasLimit' => !is_null($this->gasLimit) ? $this->gasLimit->val() : null,
			'gasPrice' => !is_null($this->gasPrice) ? $this->gasPrice->val() : null,
			'nonce' => !is_null($this->nonce) ? $this->nonce->val() : null,
			'receipt' => !is_null($this->receipt) ? $this->receipt->toArray() : null,
			'senderPubKey' => !is_null($this->senderPubKey) ? $this->senderPubKey->val() : null,
			'signature' => !is_null($this->signature) ? $this->signature->val() : null,
			'toAddr' => !is_null($this->toAddr) ? $this->toAddr->val() : null,
			'version' => !is_null($this->version) ? $this->version->val() : null,
			'code' => !is_null($this->code) ? $this->code->val() : null,
			'data' => !is_null($this->data) ? $this->data->val() : null,
		];
	}
}