<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Transaction.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Transaction extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash
	 */
	public $ID;

	/**
	 * @var ZilliqaQuantity
	 */
	public $amount;

	/**
	 * @var ZilliqaQuantity
	 */
	public $gasLimit;

	/**
	 * @var ZilliqaQuantity
	 */
	public $gasPrice;

	/**
	 * @var ZilliqaNumber
	 */
	public $nonce;

	/**
	 * @var Receipt
	 */
	public $receipt;

	/**
	 * @var ZilliqaHash
	 */
	public $senderPubKey;

	/**
	 * @var ZilliqaSignature
	 */
	public $signature;

	/**
	 * @var ZilliqaBech32
	 */
	public $toAddr;

	/**
	 * @var ZilliqaNumber
	 */
	public $version;

	/**
	 * @param ZilliqaHash $ID
	 * @param ZilliqaQuantity $amount
	 * @param ZilliqaQuantity $gasLimit
	 * @param ZilliqaQuantity $gasPrice
	 * @param ZilliqaNumber $nonce
	 * @param $receipt
	 * @param ZilliqaHash $senderPubKey
	 * @param ZilliqaSignature $signature
	 * @param ZilliqaBech32 $toAddr
	 * @param ZilliqaNumber $version
	 */
	public function __construct(ZilliqaHash $ID, ZilliqaQuantity $amount, ZilliqaQuantity $gasLimit, ZilliqaQuantity $gasPrice, ZilliqaNumber $nonce, $receipt, ZilliqaHash $senderPubKey, ZilliqaSignature $signature, ZilliqaBech32 $toAddr, ZilliqaNumber $version) {
		$this->ID = $ID;  
		$this->amount = $amount;  
		$this->gasLimit = $gasLimit;  
		$this->gasPrice = $gasPrice;  
		$this->nonce = $nonce;  
		$this->receipt = $receipt;  
		$this->senderPubKey = $senderPubKey;  
		$this->signature = $signature;  
		$this->toAddr = $toAddr;  
		$this->version = $version;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'ID' => 'ZilliqaHash',
			'amount' => 'ZilliqaQuantity',
			'gasLimit' => 'ZilliqaQuantity',
			'gasPrice' => 'ZilliqaQuantity',
			'nonce' => 'ZilliqaNumber',
			'receipt' => 'Receipt',
			'senderPubKey' => 'ZilliqaHash',
			'signature' => 'ZilliqaSignature',
			'toAddr' => 'ZilliqaBech32',
			'version' => 'ZilliqaNumber',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'ID' => $this->ID->val(),
			'amount' => $this->amount->val(),
			'gasLimit' => $this->gasLimit->val(),
			'gasPrice' => $this->gasPrice->val(),
			'nonce' => $this->nonce->val(),
			'receipt' => $this->receipt->toArray(),
			'senderPubKey' => $this->senderPubKey->val(),
			'signature' => $this->signature->val(),
			'toAddr' => $this->toAddr->val(),
			'version' => $this->version->val(),
		];
	}
}