<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type Transition.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class Transition extends ZilliqaDataType {

	/**
	 * @var ZilliqaBech32
	 */
	public $addr;

	/**
	 * @var ZilliqaNumber
	 */
	public $depth;

	/**
	 * @var Message
	 */
	public $msg;

	/**
	 * @param ZilliqaBech32 $addr
	 * @param ZilliqaNumber $depth
	 * @param $msg
	 */
	public function __construct(ZilliqaBech32 $addr, ZilliqaNumber $depth, $msg) {
		$this->addr = $addr;  
		$this->depth = $depth;  
		$this->msg = $msg;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'addr' => 'ZilliqaBech32',
			'depth' => 'ZilliqaNumber',
			'msg' => 'Message',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'addr' => $this->addr->val(),
			'depth' => $this->depth->val(),
			'msg' => $this->msg->toArray(),
		];
	}
}