<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type TxBlockBody.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class TxBlockBody extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash
	 */
	public $BlockHash;

	/**
	 * @var ZilliqaSignature
	 */
	public $HeaderSign;

	/**
	 * @var MicroBlockInfo[]
	 */
	public $MicroBlockInfos;

	/**
	 * @param ZilliqaHash $BlockHash
	 * @param ZilliqaSignature $HeaderSign
	 * @param array $MicroBlockInfos Array of MicroBlockInfo
	 */
	public function __construct(ZilliqaHash $BlockHash, ZilliqaSignature $HeaderSign, array $MicroBlockInfos) {
		$this->BlockHash = $BlockHash;
		$this->HeaderSign = $HeaderSign;
		$this->MicroBlockInfos = $MicroBlockInfos;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'BlockHash' => 'ZilliqaHash',
			'HeaderSign' => 'ZilliqaSignature',
			'MicroBlockInfos' => '[MicroBlockInfo]',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'BlockHash' => !is_null($this->BlockHash) ?? $this->BlockHash->val(),
			'HeaderSign' => !is_null($this->HeaderSign) ?? $this->HeaderSign->val(),
			'MicroBlockInfos' => !is_null($this->MicroBlockInfos) ?? \Zilliqa\Zilliqa::valueArray($this->MicroBlockInfos, 'MicroBlockInfo'),
		];
	}
}