<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type TxBlockListings.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class TxBlockListings extends ZilliqaDataType {

	/**
	 * @var TxBlockListing[]
	 */
	public $data;

	/**
	 * @var ZilliqaNumber
	 */
	public $maxPages;

	/**
	 * @param array $data Array of TxBlockListing
	 * @param ZilliqaNumber $maxPages
	 */
	public function __construct(array $data, ZilliqaNumber $maxPages) {
		$this->data = $data;
		$this->maxPages = $maxPages;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'data' => '[TxBlockListing]',
			'maxPages' => 'ZilliqaNumber',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'data' => !is_null($this->data) ?? \Zilliqa\Zilliqa::valueArray($this->data, 'TxBlockListing'),
			'maxPages' => !is_null($this->maxPages) ?? $this->maxPages->val(),
		];
	}
}