<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type TxBlockHeader.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class TxBlockHeader extends ZilliqaDataType {

	/**
	 * @var ZilliqaNumber
	 */
	public $BlockNum;

	/**
	 * @var ZilliqaNumber
	 */
	public $DSBlockNum;

	/**
	 * @var ZilliqaQuantity
	 */
	public $GasLimit;

	/**
	 * @var ZilliqaQuantity
	 */
	public $GasUsed;

	/**
	 * @var ZilliqaHash
	 */
	public $MbInfoHash;

	/**
	 * @var ZilliqaHash
	 */
	public $MinerPubKey;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumMicroBlocks;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumPages;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumTxns;

	/**
	 * @var ZilliqaHash
	 */
	public $PrevBlockHash;

	/**
	 * @var ZilliqaQuantity
	 */
	public $Rewards;

	/**
	 * @var ZilliqaHash
	 */
	public $StateDeltaHash;

	/**
	 * @var ZilliqaHash
	 */
	public $StateRootHash;

	/**
	 * @var ZilliqaTimestamp
	 */
	public $Timestamp;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TxnFees;

	/**
	 * @var ZilliqaNumber
	 */
	public $Version;

	/**
	 * @param ZilliqaNumber $BlockNum
	 * @param ZilliqaNumber $DSBlockNum
	 * @param ZilliqaQuantity $GasLimit
	 * @param ZilliqaQuantity $GasUsed
	 * @param ZilliqaHash $MbInfoHash
	 * @param ZilliqaHash $MinerPubKey
	 * @param ZilliqaNumber $NumMicroBlocks
	 * @param ZilliqaNumber $NumPages
	 * @param ZilliqaNumber $NumTxns
	 * @param ZilliqaHash $PrevBlockHash
	 * @param ZilliqaQuantity $Rewards
	 * @param ZilliqaHash $StateDeltaHash
	 * @param ZilliqaHash $StateRootHash
	 * @param ZilliqaTimestamp $Timestamp
	 * @param ZilliqaQuantity $TxnFees
	 * @param ZilliqaNumber $Version
	 */
	public function __construct(ZilliqaNumber $BlockNum, ZilliqaNumber $DSBlockNum, ZilliqaQuantity $GasLimit, ZilliqaQuantity $GasUsed, ZilliqaHash $MbInfoHash, ZilliqaHash $MinerPubKey, ZilliqaNumber $NumMicroBlocks, ZilliqaNumber $NumPages, ZilliqaNumber $NumTxns, ZilliqaHash $PrevBlockHash, ZilliqaQuantity $Rewards, ZilliqaHash $StateDeltaHash, ZilliqaHash $StateRootHash, ZilliqaTimestamp $Timestamp, ZilliqaQuantity $TxnFees, ZilliqaNumber $Version) {
		$this->BlockNum = $BlockNum;  
		$this->DSBlockNum = $DSBlockNum;  
		$this->GasLimit = $GasLimit;  
		$this->GasUsed = $GasUsed;  
		$this->MbInfoHash = $MbInfoHash;  
		$this->MinerPubKey = $MinerPubKey;  
		$this->NumMicroBlocks = $NumMicroBlocks;  
		$this->NumPages = $NumPages;  
		$this->NumTxns = $NumTxns;  
		$this->PrevBlockHash = $PrevBlockHash;  
		$this->Rewards = $Rewards;  
		$this->StateDeltaHash = $StateDeltaHash;  
		$this->StateRootHash = $StateRootHash;  
		$this->Timestamp = $Timestamp;  
		$this->TxnFees = $TxnFees;  
		$this->Version = $Version;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'BlockNum' => 'ZilliqaNumber',
			'DSBlockNum' => 'ZilliqaNumber',
			'GasLimit' => 'ZilliqaQuantity',
			'GasUsed' => 'ZilliqaQuantity',
			'MbInfoHash' => 'ZilliqaHash',
			'MinerPubKey' => 'ZilliqaHash',
			'NumMicroBlocks' => 'ZilliqaNumber',
			'NumPages' => 'ZilliqaNumber',
			'NumTxns' => 'ZilliqaNumber',
			'PrevBlockHash' => 'ZilliqaHash',
			'Rewards' => 'ZilliqaQuantity',
			'StateDeltaHash' => 'ZilliqaHash',
			'StateRootHash' => 'ZilliqaHash',
			'Timestamp' => 'ZilliqaTimestamp',
			'TxnFees' => 'ZilliqaQuantity',
			'Version' => 'ZilliqaNumber',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		return [
			'BlockNum' => $this->BlockNum->val(),
			'DSBlockNum' => $this->DSBlockNum->val(),
			'GasLimit' => $this->GasLimit->val(),
			'GasUsed' => $this->GasUsed->val(),
			'MbInfoHash' => $this->MbInfoHash->val(),
			'MinerPubKey' => $this->MinerPubKey->val(),
			'NumMicroBlocks' => $this->NumMicroBlocks->val(),
			'NumPages' => $this->NumPages->val(),
			'NumTxns' => $this->NumTxns->val(),
			'PrevBlockHash' => $this->PrevBlockHash->val(),
			'Rewards' => $this->Rewards->val(),
			'StateDeltaHash' => $this->StateDeltaHash->val(),
			'StateRootHash' => $this->StateRootHash->val(),
			'Timestamp' => $this->Timestamp->val(),
			'TxnFees' => $this->TxnFees->val(),
			'Version' => $this->Version->val(),
		];
	}
}