<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaDsBlock.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaDsBlock extends ZilliqaDataType {

	/**
	 * @var ZilliqaDsBlockHeader
	 */
	public $header;

	/**
	 * @var ZilliqaSignature
	 */
	public $signature;

	/**
	 * @param ZilliqaDsBlockHeader $header
	 * @param ZilliqaSignature $signature
	 */
	public function __construct(ZilliqaDsBlockHeader $header, ZilliqaSignature $signature) {
		$this->header = $header;  
		$this->signature = $signature;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'header' => 'ZilliqaDsBlockHeader',
			'signature' => 'ZilliqaSignature',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->header) ?? $return['header'] = $this->header->val();
		!is_null($this->signature) ?? $return['signature'] = $this->signature->val();
		return $return;
	}
}