<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaTxBlock.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaTxBlock extends ZilliqaDataType {

	/**
	 * @var ZilliqaTxBlockBody
	 */
	public $body;

	/**
	 * @var ZilliqaTxBlockHeader
	 */
	public $header;

	/**
	 * @param ZilliqaTxBlockBody $body
	 * @param ZilliqaTxBlockHeader $header
	 */
	public function __construct(ZilliqaTxBlockBody $body, ZilliqaTxBlockHeader $header) {
		$this->body = $body;  
		$this->header = $header;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'body' => 'ZilliqaTxBlockBody',
			'header' => 'ZilliqaTxBlockHeader',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->body) ?? $return['body'] = $this->body->val();
		!is_null($this->header) ?? $return['header'] = $this->header->val();
		return $return;
	}
}