<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaDSBlockListings.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaDSBlockListings extends ZilliqaDataType {

	/**
	 * @var ZilliqaDSBlockListing[]
	 */
	public $data;

	/**
	 * @var ZilliqaNumber
	 */
	public $maxPages;

	/**
	 * @param array $data Array of ZilliqaDSBlockListing
	 * @param ZilliqaNumber $maxPages
	 */
	public function __construct(array $data, ZilliqaNumber $maxPages) {
		$this->data = $data;  
		$this->maxPages = $maxPages;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'data' => '[ZilliqaDSBlockListing]',
			'maxPages' => 'ZilliqaNumber',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->data) ?? $return['data'] = \Zilliqa\Zilliqa::valueArray($this->data, 'ZilliqaDSBlockListing');
		!is_null($this->maxPages) ?? $return['maxPages'] = $this->maxPages->val();
		return $return;
	}
}