<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaTxBlockHeader.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaTxBlockHeader extends ZilliqaDataType {

	/**
	 * @var ZilliqaNumber
	 */
	public $BlockNum;

	/**
	 * @var ZilliqaNumber
	 */
	public $DSBlockNum;

	/**
	 * @var ZilliqaQuantity
	 */
	public $GasLimit;

	/**
	 * @var ZilliqaQuantity
	 */
	public $GasUsed;

	/**
	 * @var ZilliqaHash
	 */
	public $MbInfoHash;

	/**
	 * @var ZilliqaHash
	 */
	public $MinerPubKey;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumMicroBlocks;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumPages;

	/**
	 * @var ZilliqaNumber
	 */
	public $NumTxns;

	/**
	 * @var ZilliqaHash
	 */
	public $PrevBlockHash;

	/**
	 * @var ZilliqaQuantity
	 */
	public $Rewards;

	/**
	 * @var ZilliqaHash
	 */
	public $StateDeltaHash;

	/**
	 * @var ZilliqaHash
	 */
	public $StateRootHash;

	/**
	 * @var ZilliqaTimestamp
	 */
	public $Timestamp;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TxnFees;

	/**
	 * @var ZilliqaNumber
	 */
	public $Version;

	/**
	 * @param ZilliqaNumber $BlockNum
	 * @param ZilliqaNumber $DSBlockNum
	 * @param ZilliqaQuantity $GasLimit
	 * @param ZilliqaQuantity $GasUsed
	 * @param ZilliqaHash $MbInfoHash
	 * @param ZilliqaHash $MinerPubKey
	 * @param ZilliqaNumber $NumMicroBlocks
	 * @param ZilliqaNumber $NumPages
	 * @param ZilliqaNumber $NumTxns
	 * @param ZilliqaHash $PrevBlockHash
	 * @param ZilliqaQuantity $Rewards
	 * @param ZilliqaHash $StateDeltaHash
	 * @param ZilliqaHash $StateRootHash
	 * @param ZilliqaTimestamp $Timestamp
	 * @param ZilliqaQuantity $TxnFees
	 * @param ZilliqaNumber $Version
	 */
	public function __construct(ZilliqaNumber $BlockNum, ZilliqaNumber $DSBlockNum, ZilliqaQuantity $GasLimit, ZilliqaQuantity $GasUsed, ZilliqaHash $MbInfoHash, ZilliqaHash $MinerPubKey, ZilliqaNumber $NumMicroBlocks, ZilliqaNumber $NumPages, ZilliqaNumber $NumTxns, ZilliqaHash $PrevBlockHash, ZilliqaQuantity $Rewards, ZilliqaHash $StateDeltaHash, ZilliqaHash $StateRootHash, ZilliqaTimestamp $Timestamp, ZilliqaQuantity $TxnFees, ZilliqaNumber $Version) {
		$this->BlockNum = $BlockNum;  
		$this->DSBlockNum = $DSBlockNum;  
		$this->GasLimit = $GasLimit;  
		$this->GasUsed = $GasUsed;  
		$this->MbInfoHash = $MbInfoHash;  
		$this->MinerPubKey = $MinerPubKey;  
		$this->NumMicroBlocks = $NumMicroBlocks;  
		$this->NumPages = $NumPages;  
		$this->NumTxns = $NumTxns;  
		$this->PrevBlockHash = $PrevBlockHash;  
		$this->Rewards = $Rewards;  
		$this->StateDeltaHash = $StateDeltaHash;  
		$this->StateRootHash = $StateRootHash;  
		$this->Timestamp = $Timestamp;  
		$this->TxnFees = $TxnFees;  
		$this->Version = $Version;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'BlockNum' => 'ZilliqaNumber',
			'DSBlockNum' => 'ZilliqaNumber',
			'GasLimit' => 'ZilliqaQuantity',
			'GasUsed' => 'ZilliqaQuantity',
			'MbInfoHash' => 'ZilliqaHash',
			'MinerPubKey' => 'ZilliqaHash',
			'NumMicroBlocks' => 'ZilliqaNumber',
			'NumPages' => 'ZilliqaNumber',
			'NumTxns' => 'ZilliqaNumber',
			'PrevBlockHash' => 'ZilliqaHash',
			'Rewards' => 'ZilliqaQuantity',
			'StateDeltaHash' => 'ZilliqaHash',
			'StateRootHash' => 'ZilliqaHash',
			'Timestamp' => 'ZilliqaTimestamp',
			'TxnFees' => 'ZilliqaQuantity',
			'Version' => 'ZilliqaNumber',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->BlockNum) ?? $return['BlockNum'] = $this->BlockNum->val();
		!is_null($this->DSBlockNum) ?? $return['DSBlockNum'] = $this->DSBlockNum->val();
		!is_null($this->GasLimit) ?? $return['GasLimit'] = $this->GasLimit->val();
		!is_null($this->GasUsed) ?? $return['GasUsed'] = $this->GasUsed->val();
		!is_null($this->MbInfoHash) ?? $return['MbInfoHash'] = $this->MbInfoHash->val();
		!is_null($this->MinerPubKey) ?? $return['MinerPubKey'] = $this->MinerPubKey->val();
		!is_null($this->NumMicroBlocks) ?? $return['NumMicroBlocks'] = $this->NumMicroBlocks->val();
		!is_null($this->NumPages) ?? $return['NumPages'] = $this->NumPages->val();
		!is_null($this->NumTxns) ?? $return['NumTxns'] = $this->NumTxns->val();
		!is_null($this->PrevBlockHash) ?? $return['PrevBlockHash'] = $this->PrevBlockHash->val();
		!is_null($this->Rewards) ?? $return['Rewards'] = $this->Rewards->val();
		!is_null($this->StateDeltaHash) ?? $return['StateDeltaHash'] = $this->StateDeltaHash->val();
		!is_null($this->StateRootHash) ?? $return['StateRootHash'] = $this->StateRootHash->val();
		!is_null($this->Timestamp) ?? $return['Timestamp'] = $this->Timestamp->val();
		!is_null($this->TxnFees) ?? $return['TxnFees'] = $this->TxnFees->val();
		!is_null($this->Version) ?? $return['Version'] = $this->Version->val();
		return $return;
	}
}