<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaTxBlockBody.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaTxBlockBody extends ZilliqaDataType {

	/**
	 * @var ZilliqaHash
	 */
	public $BlockHash;

	/**
	 * @var ZilliqaSignature
	 */
	public $HeaderSign;

	/**
	 * @var ZilliqaMicroBlockInfo[]
	 */
	public $MicroBlockInfos;

	/**
	 * @param ZilliqaHash $BlockHash
	 * @param ZilliqaSignature $HeaderSign
	 * @param array $MicroBlockInfos Array of ZilliqaMicroBlockInfo
	 */
	public function __construct(ZilliqaHash $BlockHash, ZilliqaSignature $HeaderSign, array $MicroBlockInfos) {
		$this->BlockHash = $BlockHash;  
		$this->HeaderSign = $HeaderSign;  
		$this->MicroBlockInfos = $MicroBlockInfos;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'BlockHash' => 'ZilliqaHash',
			'HeaderSign' => 'ZilliqaSignature',
			'MicroBlockInfos' => '[ZilliqaMicroBlockInfo]',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->BlockHash) ?? $return['BlockHash'] = $this->BlockHash->val();
		!is_null($this->HeaderSign) ?? $return['HeaderSign'] = $this->HeaderSign->val();
		!is_null($this->MicroBlockInfos) ?? $return['MicroBlockInfos'] = \Zilliqa\Zilliqa::valueArray($this->MicroBlockInfos, 'ZilliqaMicroBlockInfo');
		return $return;
	}
}