<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaShardingStructure.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaShardingStructure extends ZilliqaDataType {

	/**
	 * @var ZilliqaNumber[]
	 */
	public $NumPeers;

	/**
	 * @param array $NumPeers Array of ZilliqaNumber
	 */
	public function __construct(array $NumPeers) {
		$this->NumPeers = $NumPeers;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'NumPeers' => '[ZilliqaNumber]',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->NumPeers) ?? $return['NumPeers'] = \Zilliqa\Zilliqa::valueArray($this->NumPeers, 'ZilliqaNumber');
		return $return;
	}
}