<?php
/**
 * @file
 * This is a file generated by scripts/generate-complex-datatypes.php.
 *
 * DO NOT EDIT THIS FILE.
 *
 * @ingroup generated
 * @ingroup dataTypesComplex
 */
namespace Zilliqa\DataType;

/**
 * Zilliqa data type ZilliqaBlockchainInfo.
 * 
 * Generated by scripts/generate-complex-datatypes.php based on resources/zilliqa-schema.json.
 */
class ZilliqaBlockchainInfo extends ZilliqaDataType {

	/**
	 * @var ZilliqaQuantity
	 */
	public $CurrentDSEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $CurrentMiniEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $DSBlockRate;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumDSBlocks;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumPeers;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTransactions;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxBlocks;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxnsDSEpoch;

	/**
	 * @var ZilliqaQuantity
	 */
	public $NumTxnsTxEpoch;

	/**
	 * @var ZilliqaShardingStructure[]
	 */
	public $ShardingStructure;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TransactionRate;

	/**
	 * @var ZilliqaQuantity
	 */
	public $TxBlockRate;

	/**
	 * @param ZilliqaQuantity $CurrentDSEpoch
	 * @param ZilliqaQuantity $CurrentMiniEpoch
	 * @param ZilliqaQuantity $DSBlockRate
	 * @param ZilliqaQuantity $NumDSBlocks
	 * @param ZilliqaQuantity $NumPeers
	 * @param ZilliqaQuantity $NumTransactions
	 * @param ZilliqaQuantity $NumTxBlocks
	 * @param ZilliqaQuantity $NumTxnsDSEpoch
	 * @param ZilliqaQuantity $NumTxnsTxEpoch
	 * @param array $ShardingStructure Array of ZilliqaShardingStructure
	 * @param ZilliqaQuantity $TransactionRate
	 * @param ZilliqaQuantity $TxBlockRate
	 */
	public function __construct(ZilliqaQuantity $CurrentDSEpoch, ZilliqaQuantity $CurrentMiniEpoch, ZilliqaQuantity $DSBlockRate, ZilliqaQuantity $NumDSBlocks, ZilliqaQuantity $NumPeers, ZilliqaQuantity $NumTransactions, ZilliqaQuantity $NumTxBlocks, ZilliqaQuantity $NumTxnsDSEpoch, ZilliqaQuantity $NumTxnsTxEpoch, array $ShardingStructure, ZilliqaQuantity $TransactionRate, ZilliqaQuantity $TxBlockRate) {
		$this->CurrentDSEpoch = $CurrentDSEpoch;  
		$this->CurrentMiniEpoch = $CurrentMiniEpoch;  
		$this->DSBlockRate = $DSBlockRate;  
		$this->NumDSBlocks = $NumDSBlocks;  
		$this->NumPeers = $NumPeers;  
		$this->NumTransactions = $NumTransactions;  
		$this->NumTxBlocks = $NumTxBlocks;  
		$this->NumTxnsDSEpoch = $NumTxnsDSEpoch;  
		$this->NumTxnsTxEpoch = $NumTxnsTxEpoch;  
		$this->ShardingStructure = $ShardingStructure;  
		$this->TransactionRate = $TransactionRate;  
		$this->TxBlockRate = $TxBlockRate;
	}

	/**
	 * @return array
	 */
	public static function getTypeArray(): array {
		return [
			'CurrentDSEpoch' => 'ZilliqaQuantity',
			'CurrentMiniEpoch' => 'ZilliqaQuantity',
			'DSBlockRate' => 'ZilliqaQuantity',
			'NumDSBlocks' => 'ZilliqaQuantity',
			'NumPeers' => 'ZilliqaQuantity',
			'NumTransactions' => 'ZilliqaQuantity',
			'NumTxBlocks' => 'ZilliqaQuantity',
			'NumTxnsDSEpoch' => 'ZilliqaQuantity',
			'NumTxnsTxEpoch' => 'ZilliqaQuantity',
			'ShardingStructure' => '[ZilliqaShardingStructure]',
			'TransactionRate' => 'ZilliqaQuantity',
			'TxBlockRate' => 'ZilliqaQuantity',
		];
	}

	/**
	 * Returns array with values.
	 *
	 * @return array
	 */
	public function toArray(): array {
		$return = [];
		!is_null($this->CurrentDSEpoch) ?? $return['CurrentDSEpoch'] = $this->CurrentDSEpoch->val();
		!is_null($this->CurrentMiniEpoch) ?? $return['CurrentMiniEpoch'] = $this->CurrentMiniEpoch->val();
		!is_null($this->DSBlockRate) ?? $return['DSBlockRate'] = $this->DSBlockRate->val();
		!is_null($this->NumDSBlocks) ?? $return['NumDSBlocks'] = $this->NumDSBlocks->val();
		!is_null($this->NumPeers) ?? $return['NumPeers'] = $this->NumPeers->val();
		!is_null($this->NumTransactions) ?? $return['NumTransactions'] = $this->NumTransactions->val();
		!is_null($this->NumTxBlocks) ?? $return['NumTxBlocks'] = $this->NumTxBlocks->val();
		!is_null($this->NumTxnsDSEpoch) ?? $return['NumTxnsDSEpoch'] = $this->NumTxnsDSEpoch->val();
		!is_null($this->NumTxnsTxEpoch) ?? $return['NumTxnsTxEpoch'] = $this->NumTxnsTxEpoch->val();
		!is_null($this->ShardingStructure) ?? $return['ShardingStructure'] = \Zilliqa\Zilliqa::valueArray($this->ShardingStructure, 'ZilliqaShardingStructure');
		!is_null($this->TransactionRate) ?? $return['TransactionRate'] = $this->TransactionRate->val();
		!is_null($this->TxBlockRate) ?? $return['TxBlockRate'] = $this->TxBlockRate->val();
		return $return;
	}
}