version: 2.1

orbs:
  php-coveralls: nekman/php-coveralls@2.0.0
  composer: stockfiller/composer@1
  phpunit: stockfiller/phpunit@1

executors:
  default:
    docker:
      - image: php:7.4-alpine
    resource_class: small

jobs:
  integration-test:
    executor: default
    steps:
      - run: &pcov
          name: Install PCOV and git
          command: |-
            apk add --update --no-cache git
            pecl install pcov-1.0.6
            docker-php-ext-enable pcov
      - checkout
      - composer/install_bin
      - phpunit/test:
          src-path: src
          test-path: tests
          coverage: clover
          coverage-path: coverage/clover.xml
      - php-coveralls/upload:
          clover-path: coverage/clover.xml

workflows:
  integration-test_deploy:
    jobs:
      - integration-test
      - php-coveralls/generate_upload:
          name: integration-test-job-generate_upload
          clover-path: coverage/clover.xml
          root-dir: tests
          executor: default
          pre-steps:
            - run: *pcov
            - composer/install_bin
          generate-steps:
            - phpunit/test:
                src-path: src
                test-path: tests
                coverage: clover
                coverage-path: tests/coverage/clover.xml