version: 2.1
orbs:
  php: circleci/php@1.1.0
  docker: circleci/docker@1.7.0
  node: circleci/node@4.7.0
 
workflows:
  build-and-test:
    jobs:
      - build_and_test:
          context:
            - docker
jobs:
  build_and_test:
    docker:
      - image: circleci/php:8.0.10-cli-buster
    steps:
      - checkout
      - docker/install-docker-tools
      - run: |
          sudo apt update -y &&
          sudo apt install -y libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libgmp-dev re2c libmhash-dev libmcrypt-dev file zlib1g-dev  &&
          sudo ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/

      - run: mkdir ./php-ext-cache/
      - restore_cache:
          keys:
            - extensions-v1-{{ checksum ".circleci/scripts/install-php-extensions.sh" }}
            - extensions-v1-
      - run:
          name: Copying restored extensions cache into extensions directory
          command: sudo cp -R ./php-ext-cache/. /usr/local/lib/php/extensions/no-debug-non-zts-20190902/
      - run:
          name: Install Extensions (if not cached)
          command: |
            ls -al  /usr/local/include/php/
            if [ true || ! -f /usr/local/lib/php/extensions/no-debug-non-zts-20190902/mcrypt.so ]; then
              .circleci/scripts/install-php-extensions.sh;
            fi
            ls -al  /usr/local/include/php/
      - run:
          name: Copying extensions to temp directory for caching
          command: sudo cp -R /usr/local/lib/php/extensions/no-debug-non-zts-20190902/* ./php-ext-cache/
      - save_cache:
          key: extensions-v1-{{ checksum ".circleci/scripts/install-php-extensions.sh" }}
          paths:
            - ./php-ext-cache/

      - php/install-composer:
          install-version: 2.1.6
      - php/install-packages

      - run:
          name: View PHP & Composer environment
          command: |
            php -v &&
            composer --version &&
            ./vendor/bin/phpunit --version
      - run:
          name: Phpunit tests
          command: |
            ./vendor/bin/phpunit --log-junit test-results/phpunit/junit.xml
      - store_test_results:
          path: test-results
