version: 2.1
orbs:
  php: circleci/php@1.1.0
  docker: circleci/docker@1.6.0
  node: circleci/node@4.5.0

workflows:
  build-and-test:
    jobs:
      - build_and_test:
          context:
            - docker
jobs:
  build_and_test:
    docker:
      - image: circleci/php:7.4.9-cli-buster
    steps:
      - checkout