<?php

/**
 * @file
 * Generates interface Web3Methods.
 *
 * Generating from resources/zilliqa-schema.json -> objects.
 *
 * @ingroup generators
 */

require_once(__DIR__ . "/generator-commons.php");

use gossi\codegen\generator\CodeGenerator;
use gossi\codegen\model\PhpInterface;
use gossi\codegen\model\PhpTrait;
use gossi\codegen\model\PhpMethod;
use gossi\codegen\model\PhpParameter;
use Zilliqa\DataType\ZilliqaData;


// For Tests we can disable the file generation.
$shouldWriteToDisc = !((isset($GLOBALS['argv'][1]) && $GLOBALS['argv'][1] === '--no-file-generation'));


/**
 * @var array $conf Set up variables for the generated scripts.
 */
$conf = [
    'interface' => [
        'destination' => './src/Web3Interface.php',
        'class' => 'PhpInterface',
        'name' => 'Web3Interface',
        'group' => "@ingroup generated\n * @ingroup interfaces"
    ],
    'trait' => [
        'destination' => './src/Web3Methods.php',
        'class' => 'PhpTrait',
        'name' => 'Web3Methods',
        'group' => '@ingroup generated'
    ]
];

foreach ($conf as $cnf) {
    echo "### GENERATING ZILLIQA METHODS INTERFACE ###\n";
    echo "# File generated " . $cnf['destination'] . "\n";

    $group = $cnf["group"];
    $file_header = <<<EOF
<?php
/**
 * @file
 * This is a file generated by scripts/generate-methods.php.
 * 
 * DO NOT EDIT THIS FILE.
 * 
 * $group
 */


EOF;

    /** @var $useStatements - array collects data types. */
    $useStatements = [];

    if ($cnf['class'] === 'PhpTrait') {
        $code = new PhpTrait();
    }
    if ($cnf['class'] === 'PhpInterface') {
        $code = new PhpInterface();
    }


    $code->setQualifiedName('\\Zilliqa\\' . $cnf['name'])
        ->setDescription(array(
            'Zilliqa JsonRPC Methods.',
            '',
            'Interface is generated by scripts/generate-methods.php based on resources/zilliqa-schema.json.',
            'Methods are actually implemented with [method overloading](http://php.net/manual/en/language.oop5.overloading.php#object.call) using __call().',
        ))
    ;

    $schema = getSchema();

    foreach ($schema['methods'] as $method_name => $params) {
        $valid_params = $params[0];
        $methodParams = [];
        if (count($valid_params)) {
            foreach ($valid_params as $i => $type) {
                $primitiveType = ZilliqaData::typeMap($type);
                $paramType = $primitiveType ?: $type;
                $methodParams[] = PhpParameter::create("arg" . ($i + 1))->setType($paramType);
                addUseStatement("Zilliqa\\DataType\\$paramType", $useStatements);
            }
        }

        $returnType = $params[1];
        $returnTypeDescription = '';
        if (is_array($returnType)) {
            if (ZilliqaData::typeMap($returnType[0])) {
                $arrayOfType = ZilliqaData::typeMap($returnType[0]);
            } else {
                $arrayOfType = $returnType[0];
            }
            $returnType = "array";
            $returnTypeDescription = "  Array of " . $arrayOfType;
        } else if (ZilliqaData::typeMap($returnType)) {
            $returnType = ZilliqaData::typeMap($returnType);
            addUseStatement("Zilliqa\\DataType\\$returnType", $useStatements);
        } else {
            addUseStatement("Zilliqa\\DataType\\$returnType", $useStatements);
        }

        $code->setMethod(PhpMethod::create($method_name)
            ->setDescription(array(
                "Generated method $method_name().",
                "",
                "See [Zilliqa Developer Docs $method_name](https://dev.zilliqa.com/docs/apis/" . $params[3] . ")",
                "",
            ))
            ->setParameters($methodParams)
            ->setType('?' . $returnType, $returnTypeDescription)
        );
        if ($cnf['class'] === 'PhpTrait') {
            $code->getMethod($method_name)->setBody('return $this->__call(__FUNCTION__, func_get_args());');
        }

    }

    $code->setUseStatements($useStatements);
    $generator = new CodeGenerator([
        'generateScalarTypeHints' => true,
        'generateReturnTypeHints' => true,
        'enableSorting' => false,
    ]);
    $codeText = $generator->generate($code);

    if ($shouldWriteToDisc) {
        file_put_contents($cnf['destination'] , $file_header . $codeText);
    }
    else {
        echo "File is not written to disc, because file generation is disabled by '--no-file-generation'\n";
    }
    echo "#############################################\n";
}


