<?php
/**
 * @file
 * This is a file generated by scripts/generate-methods.php.
 * 
 * DO NOT EDIT THIS FILE.
 * 
 * @ingroup generated
 * @ingroup interfaces
 */

namespace Zilliqa;

use Zilliqa\DataType\ZilliqaBech32;
use Zilliqa\DataType\ZilliqaBalance;
use Zilliqa\DataType\ZilliqaNumber;
use Zilliqa\DataType\ZilliqaDSBlockListings;
use Zilliqa\DataType\ZilliqaString;
use Zilliqa\DataType\ZilliqaBlockchainInfo;
use Zilliqa\DataType\ZilliqaQuantity;
use Zilliqa\DataType\ZilliqaDsBlock;
use Zilliqa\DataType\ZilliqaTxBlock;

/**
 * Zilliqa JsonRPC Methods.
 * 
 * Interface is generated by scripts/generate-methods.php based on resources/zilliqa-schema.json.
 * Methods are actually implemented with [method overloading](http://php.net/manual/en/language.oop5.overloading.php#object.call) using __call().
 */
interface Web3Interface {

	/**
	 * Generated method GetBalance().
	 * 
	 * See [Zilliqa Developer Docs GetBalance](https://dev.zilliqa.com/docs/apis/api-account-get-balance)
	 *
	 * @param ZilliqaBech32 $arg1
	 * @return ?ZilliqaBalance
	 */
	public function GetBalance(ZilliqaBech32 $arg1): ?ZilliqaBalance;

	/**
	 * Generated method DSBlockListing().
	 * 
	 * See [Zilliqa Developer Docs DSBlockListing](https://dev.zilliqa.com/docs/apis/api-blockchain-ds-block-listing)
	 *
	 * @param ZilliqaNumber $arg1
	 * @return ?ZilliqaDSBlockListings
	 */
	public function DSBlockListing(ZilliqaNumber $arg1): ?ZilliqaDSBlockListings;

	/**
	 * Generated method GetBlockchainInfo().
	 * 
	 * See [Zilliqa Developer Docs GetBlockchainInfo](https://dev.zilliqa.com/docs/apis/api-blockchain-get-blockchain-info)
	 *
	 * @param ZilliqaString $arg1
	 * @return ?ZilliqaBlockchainInfo
	 */
	public function GetBlockchainInfo(ZilliqaString $arg1): ?ZilliqaBlockchainInfo;

	/**
	 * Generated method GetCurrentDSEpoch().
	 * 
	 * See [Zilliqa Developer Docs GetCurrentDSEpoch](https://dev.zilliqa.com/docs/apis/api-blockchain-get-current-ds-epoch)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetCurrentDSEpoch(): ?ZilliqaQuantity;

	/**
	 * Generated method GetCurrentMiniEpoch().
	 * 
	 * See [Zilliqa Developer Docs GetCurrentMiniEpoch](https://dev.zilliqa.com/docs/apis/api-blockchain-get-current-mini-epoch)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetCurrentMiniEpoch(): ?ZilliqaQuantity;

	/**
	 * Generated method GetDsBlock().
	 * 
	 * See [Zilliqa Developer Docs GetDsBlock](https://dev.zilliqa.com/docs/apis/api-blockchain-get-ds-block)
	 *
	 * @param ZilliqaString $arg1
	 * @return ?ZilliqaDsBlock
	 */
	public function GetDsBlock(ZilliqaString $arg1): ?ZilliqaDsBlock;

	/**
	 * Generated method GetDSBlockRate().
	 * 
	 * See [Zilliqa Developer Docs GetDSBlockRate](https://dev.zilliqa.com/docs/apis/api-blockchain-get-ds-block-rate)
	 *
	 * @param ZilliqaString $arg1
	 * @return ?ZilliqaQuantity
	 */
	public function GetDSBlockRate(ZilliqaString $arg1): ?ZilliqaQuantity;

	/**
	 * Generated method GetLatestDsBlock().
	 * 
	 * See [Zilliqa Developer Docs GetLatestDsBlock](https://dev.zilliqa.com/docs/apis/api-blockchain-get-latest-ds-block)
	 *
	 * @param ZilliqaString $arg1
	 * @return ?ZilliqaDsBlock
	 */
	public function GetLatestDsBlock(ZilliqaString $arg1): ?ZilliqaDsBlock;

	/**
	 * Generated method GetLatestTxBlock().
	 * 
	 * See [Zilliqa Developer Docs GetLatestTxBlock](https://dev.zilliqa.com/docs/apis/api-blockchain-get-latest-tx-block)
	 *
	 * @param ZilliqaString $arg1
	 * @return ?ZilliqaTxBlock
	 */
	public function GetLatestTxBlock(ZilliqaString $arg1): ?ZilliqaTxBlock;

	/**
	 * Generated method GetNetworkId().
	 * 
	 * See [Zilliqa Developer Docs GetNetworkId](https://dev.zilliqa.com/docs/apis/api-blockchain-get-network-id)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNetworkId(): ?ZilliqaQuantity;

	/**
	 * Generated method GetNumDSBlocks().
	 * 
	 * See [Zilliqa Developer Docs GetNumDSBlocks](https://dev.zilliqa.com/docs/apis/api-blockchain-num-ds-blocks)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNumDSBlocks(): ?ZilliqaQuantity;

	/**
	 * Generated method GetNumTransactions().
	 * 
	 * See [Zilliqa Developer Docs GetNumTransactions](https://dev.zilliqa.com/docs/apis/api-blockchain-get-num-tx)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNumTransactions(): ?ZilliqaQuantity;

	/**
	 * Generated method GetNumTxBlocks().
	 * 
	 * See [Zilliqa Developer Docs GetNumTxBlocks](https://dev.zilliqa.com/docs/apis/api-blockchain-get-num-tx-blocks)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNumTxBlocks(): ?ZilliqaQuantity;

	/**
	 * Generated method GetPrevDifficulty().
	 * 
	 * See [Zilliqa Developer Docs GetPrevDifficulty](https://dev.zilliqa.com/docs/apis/api-blockchain-get-prev-difficulty)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetPrevDifficulty(): ?ZilliqaQuantity;

	/**
	 * Generated method GetPrevDSDifficulty().
	 * 
	 * See [Zilliqa Developer Docs GetPrevDSDifficulty](https://dev.zilliqa.com/docs/apis/api-blockchain-get-prev-ds-difficulty)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetPrevDSDifficulty(): ?ZilliqaQuantity;

	/**
	 * Generated method GetTotalCoinSupply().
	 * 
	 * See [Zilliqa Developer Docs GetTotalCoinSupply](https://dev.zilliqa.com/docs/apis/api-blockchain-get-total-coin-supply)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetTotalCoinSupply(): ?ZilliqaQuantity;

	/**
	 * Generated method GetTransactionRate().
	 * 
	 * See [Zilliqa Developer Docs GetTransactionRate](https://dev.zilliqa.com/docs/apis/api-blockchain-get-tx-rate)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetTransactionRate(): ?ZilliqaQuantity;

	/**
	 * Generated method GetTxBlockRate().
	 * 
	 * See [Zilliqa Developer Docs GetTxBlockRate](https://dev.zilliqa.com/docs/apis/api-blockchain-get-tx-block-rate)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetTxBlockRate(): ?ZilliqaQuantity;

	/**
	 * Generated method GetMinimumGasPrice().
	 * 
	 * See [Zilliqa Developer Docs GetMinimumGasPrice](https://dev.zilliqa.com/docs/apis/api-transaction-get-minimum-gas-price)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetMinimumGasPrice(): ?ZilliqaQuantity;

	/**
	 * Generated method GetNumTxnsDSEpoch().
	 * 
	 * See [Zilliqa Developer Docs GetNumTxnsDSEpoch](https://dev.zilliqa.com/docs/apis/api-transaction-get-num-txns-dsepoch)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNumTxnsDSEpoch(): ?ZilliqaQuantity;

	/**
	 * Generated method GetNumTxnsTxEpoch().
	 * 
	 * See [Zilliqa Developer Docs GetNumTxnsTxEpoch](https://dev.zilliqa.com/docs/apis/api-transaction-get-num-txns-txepoch)
	 *
	 * @return ?ZilliqaQuantity
	 */
	public function GetNumTxnsTxEpoch(): ?ZilliqaQuantity;
}